language: go
go:
  - 1.4

script:
  - go test -v
  - go install -v
after_success:
  - tar -C $HOME/gopath/bin -vzcf /tmp/horeb_linux_amd64.tar.gz horeb

deploy:
  provider: releases
  api_key:
    secure: "CGaQemsd7Ug4AYfisbYmxfWyHfjwRTRFWNswDZJt1Vbd+DdoamycyRgrMNEVkKGpJ9Z+0YvqielhoLU1GQ1QO67U55NbDsOHaiHk+lx8AMfcXGyPgOPGrRt59ccAd3pf6XljWoUzcmwg2QYqX8RWgUaAGOHFIwU/ZFSf8wbI8T4="
  file: /tmp/horeb_linux_amd64.tar.gz
  skip_cleanup: true
  on:
    tags: true
