version: "3"

services:
  # The service.
  horebd:
    build:
      context: .
      target: horebd
    image: horebd
    ports:
      - 9999:9999
    environment:
      HOREBD_DEBUG: "false"
      HOREBD_JSON: "true"

  # The client.
  horebctl:
    build:
      context: .
      target: horebctl
    image: horebctl
    environment:
      HOREBCTL_DEBUG: "false"
      HOREBCTL_HOST: horebd
