// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: horeb.proto

package horeb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RuneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num   int32  `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Block string `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
}

func (x *RuneRequest) Reset() {
	*x = RuneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_horeb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuneRequest) ProtoMessage() {}

func (x *RuneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_horeb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuneRequest.ProtoReflect.Descriptor instead.
func (*RuneRequest) Descriptor() ([]byte, []int) {
	return file_horeb_proto_rawDescGZIP(), []int{0}
}

func (x *RuneRequest) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *RuneRequest) GetBlock() string {
	if x != nil {
		return x.Block
	}
	return ""
}

type Rune struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R string `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
}

func (x *Rune) Reset() {
	*x = Rune{}
	if protoimpl.UnsafeEnabled {
		mi := &file_horeb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rune) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rune) ProtoMessage() {}

func (x *Rune) ProtoReflect() protoreflect.Message {
	mi := &file_horeb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rune.ProtoReflect.Descriptor instead.
func (*Rune) Descriptor() ([]byte, []int) {
	return file_horeb_proto_rawDescGZIP(), []int{1}
}

func (x *Rune) GetR() string {
	if x != nil {
		return x.R
	}
	return ""
}

var File_horeb_proto protoreflect.FileDescriptor

var file_horeb_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x68, 0x6f, 0x72, 0x65, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x68,
	0x6f, 0x72, 0x65, 0x62, 0x22, 0x35, 0x0a, 0x0b, 0x52, 0x75, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x14, 0x0a, 0x04, 0x52,
	0x75, 0x6e, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01,
	0x72, 0x32, 0x39, 0x0a, 0x05, 0x48, 0x6f, 0x72, 0x65, 0x62, 0x12, 0x30, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x12, 0x2e, 0x68, 0x6f, 0x72, 0x65, 0x62, 0x2e,
	0x52, 0x75, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x68, 0x6f,
	0x72, 0x65, 0x62, 0x2e, 0x52, 0x75, 0x6e, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x23, 0x5a, 0x21,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x71, 0x6a, 0x63, 0x67, 0x2f,
	0x68, 0x6f, 0x72, 0x65, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x6f, 0x72, 0x65,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_horeb_proto_rawDescOnce sync.Once
	file_horeb_proto_rawDescData = file_horeb_proto_rawDesc
)

func file_horeb_proto_rawDescGZIP() []byte {
	file_horeb_proto_rawDescOnce.Do(func() {
		file_horeb_proto_rawDescData = protoimpl.X.CompressGZIP(file_horeb_proto_rawDescData)
	})
	return file_horeb_proto_rawDescData
}

var file_horeb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_horeb_proto_goTypes = []interface{}{
	(*RuneRequest)(nil), // 0: horeb.RuneRequest
	(*Rune)(nil),        // 1: horeb.Rune
}
var file_horeb_proto_depIdxs = []int32{
	0, // 0: horeb.Horeb.GetStream:input_type -> horeb.RuneRequest
	1, // 1: horeb.Horeb.GetStream:output_type -> horeb.Rune
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_horeb_proto_init() }
func file_horeb_proto_init() {
	if File_horeb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_horeb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_horeb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rune); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_horeb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_horeb_proto_goTypes,
		DependencyIndexes: file_horeb_proto_depIdxs,
		MessageInfos:      file_horeb_proto_msgTypes,
	}.Build()
	File_horeb_proto = out.File
	file_horeb_proto_rawDesc = nil
	file_horeb_proto_goTypes = nil
	file_horeb_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HorebClient is the client API for Horeb service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HorebClient interface {
	GetStream(ctx context.Context, in *RuneRequest, opts ...grpc.CallOption) (Horeb_GetStreamClient, error)
}

type horebClient struct {
	cc grpc.ClientConnInterface
}

func NewHorebClient(cc grpc.ClientConnInterface) HorebClient {
	return &horebClient{cc}
}

func (c *horebClient) GetStream(ctx context.Context, in *RuneRequest, opts ...grpc.CallOption) (Horeb_GetStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Horeb_serviceDesc.Streams[0], "/horeb.Horeb/GetStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &horebGetStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Horeb_GetStreamClient interface {
	Recv() (*Rune, error)
	grpc.ClientStream
}

type horebGetStreamClient struct {
	grpc.ClientStream
}

func (x *horebGetStreamClient) Recv() (*Rune, error) {
	m := new(Rune)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HorebServer is the server API for Horeb service.
type HorebServer interface {
	GetStream(*RuneRequest, Horeb_GetStreamServer) error
}

// UnimplementedHorebServer can be embedded to have forward compatible implementations.
type UnimplementedHorebServer struct {
}

func (*UnimplementedHorebServer) GetStream(*RuneRequest, Horeb_GetStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetStream not implemented")
}

func RegisterHorebServer(s *grpc.Server, srv HorebServer) {
	s.RegisterService(&_Horeb_serviceDesc, srv)
}

func _Horeb_GetStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RuneRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HorebServer).GetStream(m, &horebGetStreamServer{stream})
}

type Horeb_GetStreamServer interface {
	Send(*Rune) error
	grpc.ServerStream
}

type horebGetStreamServer struct {
	grpc.ServerStream
}

func (x *horebGetStreamServer) Send(m *Rune) error {
	return x.ServerStream.SendMsg(m)
}

var _Horeb_serviceDesc = grpc.ServiceDesc{
	ServiceName: "horeb.Horeb",
	HandlerType: (*HorebServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStream",
			Handler:       _Horeb_GetStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "horeb.proto",
}
